export const theme = {
  cream: "var(--cream)",
  warmWhite: "var(--warm-white)",
  green: "var(--green)",
  deepGreen: "var(--deep-green)",
  darkGreen: "var(--dark-green)",
  orange: "var(--orange)",
  deepOrange: "var(--deep-orange)",
  brown: "var(--brown)",
  text: "var(--text)",
  muted: "var(--muted)",
  light: "var(--light)",
  danger: "var(--danger)",
  white: "var(--white)",
  shadow: "var(--shadow)",
  shadowLg: "var(--shadow-lg)",
};
