import { NextResponse, type NextRequest } from 'next/server';

/**
 * Middleware to set common security headers on all responses.
 * This acts as a lightweight alternative to using external packages like helmet.
 */
export function middleware(_request: NextRequest) {
  const response = NextResponse.next();
  void _request;

  const isDev = process.env.NODE_ENV !== "production";

  // Strict-Transport-Security: enforce HTTPS with long max-age
  response.headers.set('Strict-Transport-Security', 'max-age=63072000; includeSubDomains; preload');
  // X-Content-Type-Options: prevent MIME sniffing
  response.headers.set('X-Content-Type-Options', 'nosniff');
  // X-Frame-Options: mitigate clickjacking
  response.headers.set('X-Frame-Options', 'SAMEORIGIN');
  // X-XSS-Protection: enable basic XSS protection in older browsers
  response.headers.set('X-XSS-Protection', '1; mode=block');
  // Referrer-Policy: control referrer information
  response.headers.set('Referrer-Policy', 'strict-origin-when-cross-origin');
  // Permissions-Policy: restrict browser features
  response.headers.set(
    'Permissions-Policy',
    'geolocation=(self), microphone=(), camera=()'
  );
  // Content-Security-Policy: basic CSP; adjust sources as needed
  response.headers.set(
    'Content-Security-Policy',
    [
      "default-src 'self'", // restrict by default to same origin
      // Next.js and JSON-LD require inline scripts; dev tooling may require eval.
      `script-src 'self' 'unsafe-inline'${isDev ? " 'unsafe-eval'" : ""}`,
      // allow inline styles for dynamic styling generated by Next.js components
      "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
      "font-src 'self' data: https://fonts.gstatic.com",
      // allow HMR websockets in dev and same-origin fetches
      `connect-src 'self'${isDev ? " ws: wss:" : ""}`,
      "img-src 'self' data:" // allow data URIs for emojis/icons
    ].join('; ')
  );

  return response;
}

// Apply this middleware to all routes
export const config = {
  matcher: '/:path*',
};
